---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "This is a playbook to create an instance"

    - debug:
        msg: "There is a new image version to use on server creation"
